name: basescrollview
description: BaseScrollView handle scroll to top or scroll to bottom.
version: 0.0.8
homepage: https://github.com/hungit36/basescrollview

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
